# Generated by Django 4.2 on 2025-03-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DxfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dxf_file', models.FileField(upload_to='manual/dxf')),
                ('type', models.CharField(choices=[('DR', 'Door (bere)'), ('BL', 'Balkeni (berenda)'), ('ST', 'stairs'), ('OT', 'Other')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DXFOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dxf_file', models.FileField(upload_to='manual/dxf')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.FileField(upload_to='manual/image')),
                ('type', models.CharField(choices=[('DR', 'Door (bere)'), ('BL', 'Balkeni (berenda)'), ('ST', 'stairs'), ('OT', 'Other')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('image1', models.ImageField(upload_to=store.models.uploadTo, verbose_name='image 1')),
                ('image2', models.ImageField(blank=True, upload_to=store.models.uploadTo, verbose_name='image 2')),
                ('image3', models.ImageField(blank=True, upload_to=store.models.uploadTo, verbose_name='image 3')),
                ('dimensions_type', models.CharField(choices=[('square', 'square'), ('rectangular', 'rectangular'), ('other', 'other')], max_length=256)),
                ('diminsions', models.CharField(blank=True, max_length=256, null=True)),
                ('dimensions_info', models.TextField(blank=True, null=True)),
                ('dimensions_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('priority', models.CharField(choices=[('H', 'High'), ('S', 'Sequence')], max_length=256)),
                ('remark', models.TextField(max_length=256)),
                ('quantity', models.IntegerField(default=1)),
                ('verif_price', models.CharField(choices=[('P', 'pending'), ('A', 'Accepted'), ('D', 'Declined'), ('W', 'Waiting')], default='W', max_length=256)),
                ('verif_design', models.CharField(choices=[('P', 'pending'), ('A', 'Accepted'), ('D', 'Declined'), ('W', 'Waiting')], default='W', max_length=256)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('dxf_file', models.FileField(blank=True, null=True, upload_to=store.models.uploadDXFTo, verbose_name='dxf')),
                ('date', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('DR', 'Door (bere)'), ('BL', 'Balkeni (berenda)'), ('ST', 'stairs'), ('OT', 'Other')], max_length=256)),
                ('subclassed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('thickness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.thickness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['priority', 'date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='UserPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=256)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Is Delivered')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
