# Generated by Django 4.2 on 2025-03-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_singlematerial_quantity_alter_thickness_name'),
        ('store', '0002_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.thickness'),
        ),
    ]
