# Generated by Django 4.2 on 2025-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
