# Generated by Django 4.2 on 2025-03-04 23:04

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='date', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date (e.g., 2022/11/22)')),
                ('institution_name', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField(blank=True, help_text='Phone number of the institution', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address of the institution', max_length=254, null=True)),
                ('address', models.CharField(blank=True, help_text='Address of the institution', max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text='Description of the bill', max_length=255, null=True)),
                ('payment_details', models.CharField(help_text='Details of the payment', max_length=255)),
                ('amount', models.FloatField(help_text='Total amount due for payment', verbose_name='Total Amount Owing (Ksh)')),
                ('status', models.BooleanField(default=False, help_text='Payment status of the bill', verbose_name='Paid')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMaterial',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('total_cost', models.IntegerField()),
                ('minsceus_cost', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('credit', 'credit'), ('cash', 'cash')], max_length=256)),
                ('advance', models.IntegerField(blank=True, null=True)),
                ('leftover', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0.5, '0.5mm'), (0.7, '0.7mm'), (0.8, '0.8mm'), (0.9, '0.9mm'), (0.9, '0.9mm'), (1.0, '1.0mm'), (1.1, '1.1mm'), (1.4, '1.4mm'), (1.8, '1.8mm'), (2.5, '2.5mm'), (3.0, '3.0mm')], max_length=250, unique=True)),
                ('added', models.IntegerField()),
                ('removed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.thickness')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.inventorymaterial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='irons',
            field=models.ManyToManyField(to='bills.singlematerial'),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supplier'),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
