# Generated by Django 4.2 on 2025-03-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_thickness_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematerial',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thickness',
            name='name',
            field=models.FloatField(choices=[(0.5, '0.5mm'), (0.7, '0.7mm'), (0.8, '0.8mm'), (0.9, '0.9mm'), (1.0, '1.0mm'), (1.1, '1.1mm'), (1.4, '1.4mm'), (1.8, '1.8mm'), (2.5, '2.5mm'), (3.0, '3.0mm')], max_length=250, unique=True),
        ),
    ]
