# Generated by Django 4.2 on 2025-03-16 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_singlematerial_quantity_alter_thickness_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thickness',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='thickness',
            name='name',
            field=models.FloatField(choices=[(0.5, '0.5mm'), (0.6, '0.6mm'), (0.7, '0.7mm'), (0.8, '0.8mm'), (0.9, '0.9mm'), (0.91, '0.9(oversize)'), (1.0, '1.0mm'), (1.1, '1.1mm'), (1.4, '1.4mm'), (1.8, '1.8mm'), (2.5, '2.5mm'), (3.0, '3.0mm')], max_length=250, unique=True),
        ),
    ]
