# Generated by Django 4.2 on 2025-04-30 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee'),
        ('bills', '0005_alter_thickness_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='SaleryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
                ('total', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
    ]
