# Generated by Django 4.2 on 2025-04-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_role'),
        ('bills', '0006_remove_bill_address_remove_bill_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('ammount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('transfer', 'transfer')], max_length=150)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='proof/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
