# Generated by Django 4.2 on 2025-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_freeassets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeassets',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
