# Generated by Django 4.2 on 2025-05-01 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_clientpayment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salerypayment',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='salerypayment',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
