# Generated by Django 4.2 on 2025-05-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_alter_salerypayment_options_salerypayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(help_text='Total amount due for payment', verbose_name='Total Amount (Birr)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.CharField(blank=True, help_text='What is the expense for', max_length=255, null=True),
        ),
    ]
