# Generated by Django 4.2 on 2025-05-26 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_alter_bill_amount_alter_bill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypayment',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
