# Generated by Django 4.2 on 2025-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_alter_inventorypayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Logistics', 'Logistics'), ('PayRoll', 'PayRoll'), ('Electric', 'Electric'), ('Overtime', 'Overtime')], max_length=255),
        ),
        migrations.AlterField(
            model_name='thickness',
            name='name',
            field=models.FloatField(choices=[(0.5, '0.5mm'), (0.6, '0.6mm'), (0.7, '0.7mm'), (0.8, '0.8mm'), (0.9, '0.9mm'), (1.4, '1.4mm'), (1.8, '1.8mm'), (2.5, '2.5mm'), (1.0, '1.0mm'), (1.1, '1.1mm'), (1.2, '1.2mm'), (3.0, '3.0mm'), (0.91, '0.9mm(oversize)'), (1.11, '1.1mm(oversize)'), (1.21, '1.2mm(oversize)'), (1.01, '1.0mm(oversize)'), (1.81, '1.8mm(oversize)'), (2.51, '2.5mm(oversize)'), (1.41, '1.4mm(oversize)'), (5, '5mm'), (4, '4mm'), (0, 'scrap'), (10.0, 'self')], max_length=250, unique=True),
        ),
    ]
