# Generated by Django 4.2 on 2025-05-28 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_bill_bill_type_alter_thickness_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date (e.g., 2022/11/22)'),
        ),
    ]
