# Generated by Django 4.2 on 2025-03-20 13:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_item_date'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('paid', models.BooleanField(default=False)),
                ('ammount', models.ManyToManyField(to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='OverTimeConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('overtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.overtime')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='overtime',
            field=models.ManyToManyField(through='accounts.OverTimeConnect', to='accounts.overtime'),
        ),
    ]
