# Generated by Django 4.2 on 2025-03-20 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_overtime_overtimeconnect_myuser_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeconnect',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
