# Generated by Django 4.2 on 2025-04-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_overtimeconnect_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('designer', 'designer'), ('manager', 'manager'), ('formal', 'formal'), ('driver', 'driver'), ('accountant', 'accountant')], max_length=150)),
                ('salary', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
