# Generated by Django 4.2 on 2025-04-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('MR', 'Marketing'), ('DR', 'Designer'), ('OP', 'Operative'), ('AT', 'Accounting'), ('DL', 'Delivery'), ('AD', 'Admin'), ('GM', 'General Manager')], default='MR', max_length=12, verbose_name='Role'),
        ),
    ]
