# Generated by Django 4.2 on 2025-05-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employee_account_employee_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('MR', 'Marketing'), ('DR', 'Designer'), ('OP', 'Operative'), ('AT', 'Accounting'), ('DL', 'Delivery'), ('AD', 'Admin'), ('GM', 'General Manager'), ('SH', 'Share Holder')], default='MR', max_length=12, verbose_name='Role'),
        ),
    ]
