# Generated by Django 4.2 on 2025-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(verbose_name='Grand Total (Ksh)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(verbose_name='Total Amount (Ksh)'),
        ),
    ]
