# Generated by Django 4.2 on 2025-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_quantity_invoice_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping',
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross_cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross_profit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross_revenue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='net_profit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='opertional_cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='scrap_type',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Used', 'User'), ('Clean', 'Clean')], max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='scrap_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(),
        ),
    ]
