# Generated by Django 4.2 on 2025-05-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_invoice_grand_total_remove_invoice_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gross_cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gross_profit',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gross_revenue',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_profit',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='opertional_cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(blank=True),
        ),
    ]
